# Generated by Django 5.0 on 2023-12-28 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("nepali_name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Province",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("number", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("nepali_name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="Municipality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("nepali_name", models.CharField(max_length=255, unique=True)),
                ("longitude", models.FloatField()),
                ("latitude", models.FloatField()),
                ("average_rent_price", models.FloatField(default=0)),
                ("total_accommodations", models.IntegerField(default=0)),
                ("year_over_year_rent_change", models.FloatField(default=0)),
                ("year_over_year_rent_change_percent", models.FloatField(default=0)),
                ("rental_guide", models.TextField(default="")),
                ("description", models.TextField(default="")),
                ("is_approved", models.BooleanField(default=False, editable=False)),
                ("approved_at", models.DateTimeField(null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approved_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="location.district"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Municipalities",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="district",
            name="province",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="location.province"),
        ),
        migrations.CreateModel(
            name="Ward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("nepali_name", models.CharField(max_length=255)),
                ("number", models.IntegerField()),
                (
                    "municipality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="location.municipality"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {
                    ("name", "municipality"),
                    ("nepali_name", "municipality"),
                    ("number", "municipality"),
                },
            },
        ),
    ]
