# Generated by Django 5.0 on 2023-12-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("location", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="municipality",
            name="approved_at",
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
