# Generated by Django 5.0 on 2023-12-11 15:52

import account.models
import account.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("middle_name", models.CharField(blank=True, max_length=255, null=True)),
                ("primary_contact", models.CharField(max_length=255)),
                ("secondary_contact", models.CharField(blank=True, max_length=255, null=True)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                (
                    "account_type",
                    models.PositiveIntegerField(
                        choices=[(1, "Seeker"), (2, "Owner"), (3, "Maintainer")], default=1
                    ),
                ),
                (
                    "citizenship_number",
                    models.CharField(
                        editable=False,
                        max_length=255,
                        null=True,
                        unique=True,
                        validators=[account.validators.validate_citizenship_number],
                    ),
                ),
                (
                    "citizenship_back",
                    models.ImageField(null=True, upload_to=account.models.upload_citizenship_back_to),
                ),
                ("is_citizenship_verified", models.BooleanField(default=False, editable=False)),
                ("is_contact_verified", models.BooleanField(default=False, editable=False)),
                ("is_email_verified", models.BooleanField(default=False, editable=False)),
                ("avatar", models.ImageField(null=True, upload_to=account.models.upload_avatar_to)),
                (
                    "user",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ResetPasswordCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("is_used", models.BooleanField(default=False, editable=False)),
                ("is_expired", models.BooleanField(default=False, editable=False)),
                ("expired_at", models.DateTimeField(editable=False, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reset_password_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
