# Generated by Django 5.0 on 2023-12-08 15:17

import django.db.models.deletion
import util.helper
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_approved", models.BooleanField(default=False, editable=False)),
                ("approved_at", models.DateTimeField(auto_now_add=True)),
                ("is_pinned", models.BooleanField(default=False, editable=False)),
                ("pinned_at", models.DateTimeField(auto_now_add=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("province", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("wifi", models.BooleanField(default=False)),
                ("air_conditioning", models.BooleanField(default=False)),
                ("attached_bathroom", models.BooleanField(default=False)),
                ("max_occupancy", models.PositiveIntegerField()),
                ("rent", models.PositiveIntegerField()),
                ("availability_calendar", models.DateField()),
                ("square_feet", models.FloatField()),
                ("with_kitchen_setup", models.BooleanField(default=False)),
                ("parking_facility", models.BooleanField(default=False)),
                ("nearby_points_of_interest", models.TextField(blank=True)),
                ("is_booked", models.BooleanField(default=False)),
                ("type", models.IntegerField(blank=True, choices=[(1, "Single"), (2, "Double")], default=1)),
                ("available_furnishing", models.CharField(blank=True, max_length=255)),
                ("proximity_to_public_transport", models.CharField(blank=True, max_length=255)),
                (
                    "owner_contact_number",
                    models.CharField(max_length=10, validators=[util.helper.validate_nepali_phone_number]),
                ),
                ("floor", models.PositiveIntegerField()),
                (
                    "approved_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approved_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pinned_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pinned_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Rooms",
                "ordering": ["-created_at"],
                "unique_together": {("latitude", "longitude"), ("owner_contact_number", "floor")},
            },
        ),
    ]
