# Generated by Django 5.0 on 2023-12-08 17:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accommodation", "0002_room_rental_type_flat"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flat",
            options={"ordering": ["-created_at"], "verbose_name_plural": "Flats"},
        ),
    ]
