# Generated by Django 5.0 on 2023-12-08 15:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("util", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="media",
            options={"ordering": ["-created_at"], "verbose_name_plural": "Medias"},
        ),
    ]
