# Generated by Django 5.0 on 2023-12-08 15:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("review", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ["-created_at"], "verbose_name_plural": "Reviews"},
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("created_by", "object_id", "content_type")},
        ),
    ]
